### ISSUE TITLE
Seemingly impossible level

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#60] opened 2019-01-04 18:18 UTC
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/250
Upon first starting the Level 10 matching fractions to shape level on the Build a Fraction screen, I encountered a seemingly impossible level.  Neither @phet-steele or I could solve it.  I haven't seen other impossible levels, but will keep looking and update this issue with other instances.
Conversation:
>Kathryn Woessner [10:59 AM]
>Since you're more familiar with the mechanics, I thought I'd ask you before making an issue.  I have run into an instance where I don't think I can beat a level, but it may be that I'm missing a mechanic.  Is there a way to add a whole number to this fraction?
![cantbeat](https://user-images.githubusercontent.com/41024075/50703552-bcd3db00-1011-11e9-988b-3ba406320ca0.PNG)

>Steele Dalton [11:02 AM]
>if you can't beat a level, you need to answer other questions a different way
>let me look for a sec

>Kathryn Woessner [11:02 AM]
>I've tried, but there's no combo I can find
>It either needs to be 9/10 or 1 4/5
>Neither is possible

>Steele Dalton [11:04 AM]
>so before answering the second one, you have a 1, two 4s, a 5, and a 6?

>Kathryn Woessner [11:05 AM]
>Yes
>It could be 1 1/2, 3/2, or 6/4.  I can't figure out how to use mixed numbers and 3 was never available

>Steele Dalton [11:08 AM]
>then...I don't see how this is possible? only way to get 1.5 with those is 6/4. and if you can't use mixed numbers then you are stuck. Because I'm pretty sure 1/9 and 5/7 HAVE to be answered that way since they cannot be reduced and 2/18 or 10/14 is not an option.
>and working backwards, trying to get 1.8 as a fraction...
>9/5?
>yea 9/5
>but the nine is needed for the first one

>Kathryn Woessner [11:10 AM]
>Yeah

**Steps to reproduce:**
1. Go to the build a fraction screen
2. Select the Level 10 on the bottom row
3. If level is possible, hit refresh button to keep looking

**Screenshots:**
![cantbeat](https://user-images.githubusercontent.com/41024075/50703762-6adf8500-1012-11e9-983c-92be89ad3602.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪Build a Fraction‬
URL: https://phet-dev.colorado.edu/html/build-a-fraction/1.0.0-dev.17/phet/build-a-fraction_en_phet.html
Version: 1.0.0-dev.17 2019-01-04 01:10:24 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment] 2019-01-04 18:22
Hit refresh once, and found a seeming other instance:
![moreimpossible](https://user-images.githubusercontent.com/41024075/50703972-11c42100-1013-11e9-98fb-68b32c4f300c.PNG)

**Comment by phet-steele** [comment] 2019-01-04 18:42
Could be why `?showAnswers` asserts on this level in BAF.

**Comment by KatieWoe** [comment] 2019-01-04 19:52
Didn't try for as long, but it seems like this may be a problem in Fractions: Intro as well.
https://github.com/phetsims/QA/issues/252
![maybecant](https://user-images.githubusercontent.com/41024075/50707862-8f8e2980-101f-11e9-8c5a-0791706ad317.PNG)

**Comment by rea-laura** [comment] 2019-01-07 16:56
@jonathanolson found this problem again for https://github.com/phetsims/QA/issues/250.

Occurs in Build a Fraction > Build a Fraction > Level 6 (lower level with shapes). 
The problem only happens sometimes - most of the time the sim will give a solvable problem, but sometimes loads an unsolvable one.
![32bb65dc-ca7c-4ba4-b7d5-7865591ba4aa](https://user-images.githubusercontent.com/44005544/50781297-3b26bc00-1262-11e9-8324-3537bf1fb67f.png)

Katie also found the same problem on the corresponding introduction sim on the same level.
![image](https://user-images.githubusercontent.com/44005544/50780743-f51d2880-1260-11e9-9f5a-9a73b21cc3df.png)

**Comment by rea-laura** [comment] 2019-01-07 17:04
Found again on https://github.com/phetsims/QA/issues/250

Build a Fraction > Build a Fraction > Level 7 (lower with shapes)

**Comment by KatieWoe** [comment] 2019-01-07 18:01
Since this seems to be happening most on Build a Fraction and corresponding Fraction Intro game screens where you are matching the fraction to the shape, I collected some more exact data.  I played each of those 10 levels on Fractions Intro and recorded the possible vs impossible levels
Level: Possible: Impossible
1: 10: 0
2: 10: 0
3: 10: 0
4: 10: 0
5: 10: 0
6: 7: 3
7: 7: 3
8: 10: 0
9: 10: 0
10: 2: 8

**Comment by KatieWoe** [comment] 2019-01-07 21:42
@jonathanolson I believe this is another example.  Found on iPad, Mixed Numbers sim, Level 4, building fractions to match shapes.  https://github.com/phetsims/QA/issues/253
![image from ios](https://user-images.githubusercontent.com/41024075/50795115-70df9b00-128a-11e9-95ee-63c3796cf259.png)

**Comment by jonathanolson** [comment] 2019-01-08 19:21
> @jonathanolson I believe this is another example. Found on iPad, Mixed Numbers sim, Level 4, building fractions to match shapes. phetsims/QA#253

Would the following solve it?:
```
1 1/3
2 1/2
3 5/9
```

**Comment by KatieWoe** [comment] 2019-01-08 19:22
@jonathanolson It would.  Good catch.

**Comment by jonathanolson** [comment] 2019-01-08 19:35
Using the following hack code in console to test:

```js
const generators = _.flatten( _.range( 1, 11 ).map( n => [
  phet.fractionsCommon.FractionLevel[ `level${n}Numbers` ],
  phet.fractionsCommon.FractionLevel[ `level${n}Shapes` ],
  phet.fractionsCommon.FractionLevel[ `level${n}NumbersMixed` ],
  phet.fractionsCommon.FractionLevel[ `level${n}ShapesMixed` ],
] ) );

generators.forEach( generator => {
  console.log( generator.name );
  for ( let i = 0; i < 100; i++ ) {
    const challenge = generator( 1, phet.fractionsCommon.FractionsCommonColorProfile.shapeBlueProperty );
    challenge.cheat();
  }
} );
```

As expected, numbers level 7 is still failing (has a different root cause of unsolvability).

**Comment by jonathanolson** [comment] 2019-01-08 19:47
@ariel-phet and @amanda-phet:

I believe the level 7 numbers design doc has a mistake in the following line:

> -- Possible fractions sets from which to draw 2 each {1/2, 2/4, 3/6} , 
{1/3, 2/6, 3/9}, {2/3, 4/6, 3/9}, {1/4, 2/8}, {3/4, 6/8}

Instead of 2/3, 4/6, 3/9, I believe it should have 6/9. The resulting unsolvable levels look were resulting from this. Can I get confirmation? (Should be patched with the above commit).

**Comment by jonathanolson** [comment] 2019-01-08 19:50
Automated testing is showing 1000 generated challenges of each level are now passing.

@KatieWoe could you spot-check master to ensure levels 6/7/10 are looking solvable in general (should be the only ones affected by the changes).

**Comment by KatieWoe** [comment] 2019-01-08 20:36
Looks good on master

**Comment by jonathanolson** [comment] 2019-01-14 19:41
I'm assigned. Should I close the issue or keep it open (and unassign), or is there something to do?

**Comment by KatieWoe** [comment] 2019-01-14 19:59
Close if you feel its done.  If you think it will need more testing during rc or next dev test keep open, label appropriately, and link in next test.  Its up to your discretion.  @jonathanolson

**Comment by jonathanolson** [comment] 2019-01-15 03:02
Closing, thanks!

**Closed by jonathanolson** 2019-01-15 03:02 UTC
Labels: status:fixed-pending-testing, type:bug
