### ISSUE TITLE
Add accordion box to Mixed Numbers Intro screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/fractions-common#19] opened 2018-12-05 19:34 UTC
![image](https://user-images.githubusercontent.com/7852916/49538983-ddc9d480-f889-11e8-9f30-1f092bc43d94.png)

When minimized, the box can have the title "Equation"

**Comment by jonathanolson** [comment] 2018-12-06 18:32
Added.

It currently uses the default layout for accordion boxes which hide their title, which ends up adding additional padding on the left:
<img width="254" alt="screen shot 2018-12-06 at 11 30 51 am" src="https://user-images.githubusercontent.com/480878/49604176-7aec4200-f94a-11e8-8fad-66c1e6cc8dbb.png">

It also currently keeps the equality sign fixed in position (although we could definitely re-center during changes, which may look statically better but be worse during changes):
<img width="242" alt="screen shot 2018-12-06 at 11 31 19 am" src="https://user-images.githubusercontent.com/480878/49604204-92c3c600-f94a-11e8-918e-1df19197aabf.png">

Alternatively if we want to show the title when expanded, it would look more like:
<img width="236" alt="screen shot 2018-12-06 at 11 32 18 am" src="https://user-images.githubusercontent.com/480878/49604233-a2dba580-f94a-11e8-9028-29cf795775fc.png">

Thoughts?

**Comment by amanda-phet** [comment] 2018-12-06 21:00
We would also like the gray fraction to not appear in this box. So, instead of 4 0/5 = 20/5 would just show 4 = 20/5. 

Is it possible to make the vinculum the same width for both fractions? Seems difficult since the right fraction can have a large denominator. AP would like the one on the right a little narrower and the one on the left a little wider. Scratch that- seems like an unnecessary complication to the code.

**Comment by jonathanolson** [comment] 2018-12-11 20:36
> We would also like the gray fraction to not appear in this box. So, instead of 4 0/5 = 20/5 would just show 4 = 20/5.

Implemented.

> Is it possible to make the vinculum the same width for both fractions? Seems difficult since the right fraction can have a large denominator. AP would like the one on the right a little narrower and the one on the left a little wider. Scratch that- seems like an unnecessary complication to the code.

Let me know. It should be possible, but would just need a bit more details about desired behavior.

**Comment by phet-steele** [comment] 2019-01-04 08:12
Hovering my mouse over where the title would be if it weren't hidden (while the box is expanded) makes the top section of the box look very clickable. My cursor becomes a hand, yet clicking the top of the box does nothing (again, while it is expanded). @amanda-phet I'd suggest either clicking there closes it, or the cursor does not indicate that it can be clicked.

For phetsims/QA/issues/253.

**Comment by amanda-phet** [comment] 2019-01-04 17:39
@jonathanolson can you please change the cursor so it doesn't show a hand?

**Comment by jonathanolson** [comment] 2019-01-04 20:14
This would be a very general change to AccordionBox (not having the title bar area pickable when expanded when we don't show the title).

@ariel-phet thoughts?

**Comment by amanda-phet** [comment] 2019-01-04 20:21
>(not having the title bar area pickable when expanded when we don't show the title).

It currently isn't pickable, though, in this sim. It is showing the hand, but isn't pickable. If it's standard to be pickable let's just do that.

**Comment by ariel-phet** [comment] 2019-01-05 01:02
@jonathanolson agreed with @amanda-phet -- if the standard behavior is to have this area pickable, lets make it pickable. Since it shows the hand, it would make sense to make it pickable. 

But I agree, we should not be making general changes to AccordionBox. So which ever keeps in line with the current implementation (sounds like keeping the hand in the title bar area AND having that area actually be pickable)

**Comment by jonathanolson** [comment] 2019-01-05 01:39
I'm seeing the same behavior on area-builder and balancing-chemical-equations. This could potentially have been a regression in behavior? Checking.

**Comment by jonathanolson** [comment] 2019-01-10 23:14
I've applied a change that I should be safe for all configurations of AccordionBox, where it prevents the expanded title bar from being pickable when the title isn't shown while expanded. It looks like it's required to still be visible (since it needs to be focusable for a11y, as it is the node used for collapsing via keyboard).

@ariel-phet it would probably be good to have the change's safety reviewed by someone ideally familiar with a11y and AccordionBox.

**Comment by ariel-phet** [comment] 2019-01-11 00:32
@jessegreenberg can you take a look at this change? Very high priority as we are trying to get fractions to RC

**Comment by jessegreenberg** [comment] 2019-01-11 17:19
I can still see similar behavior in balancing-chemical-equations, the collapsed title bar has a cursor even though `options.titleBarExpandCollapse` is false. We would probably need something similar for that option too.
<details>

```js
    if ( options.titleBarExpandCollapse ) {
      this.collapsedTitleBar.addInputListener( {
        down: function() {
          self.phetioStartEvent( 'expanded' );
          self.expandedProperty.value = true;
          self.phetioEndEvent();
        }
      } );
    }
    else {
      this.collapsedTitleBar.pickable = false;
    }
```
</details>

There is a code comment:
> Ideally we wouldn't want it visible at all, however for the a11y implementation we'll want to keep it visible so it can be focused as the main accessible element while the accordion box is expanded.

I would rather have a better a11y implementation and there are other ways we can do this. Also, the current instrumentation only includes keyboard nav and nothing else for screen readers so I don't want to add workarounds for a11y since what is already there doesn't include everything. The a11y team won't be working on a sim with AccordionBox for at least 3+ months.

So here is what I would recommend:
- Save https://github.com/phetsims/sun/commit/60ffa49945937bd81461553d253f5ccad008df6d as a current reference to the state of a11y in accordion box, create a new issue to instrument AccordionBox with a11y better.
- Remove a11y from AccordionBox, which will probably fix this issue without your change because it will remove the `a11yCollapseListener` from `expandedTitleBar`.

@jonathanolson does this sound reasonable?

**Comment by jessegreenberg** [comment] 2019-01-11 21:19
@jonathanolson I removed your workaround after https://github.com/phetsims/sun/issues/444, the problem is still fixed. Can you please review?

**Comment by jonathanolson** [comment] 2019-01-11 22:32
Loos good to me, thanks!

**Closed by jonathanolson** 2019-01-11 22:32 UTC
Labels: design:general, priority:1-top
