### ISSUE TITLE
Beginning of the first "ding" sound is cut off

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#109] opened 2019-07-19 20:31 UTC
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Multiple, filmed on Edge
**Problem description:**
For https://github.com/phetsims/QA/issues/368 and https://github.com/phetsims/QA/issues/367
Didn't seem to happen when I tested published Build a Fraction, which uses similar sounds.
The first instance of the correct answer ding noise seems to be cut off at the beginning.  Most noticeable on Edge and Firefox so far, but I think it happens on chrome as well.
**Steps to reproduce:**
1. Start on a fresh refresh of the sim
2. Go to a level and get two right answers in a row.  Compare sounds.

**Screenshots:**
https://drive.google.com/file/d/1JpQMorYYv7qfAWAjl8w-EasmmUwmz3Sb/view?usp=sharing

Troubleshooting information (do not edit):

<details>

Name: ‪Fractions: Equality‬
URL: https://phet-dev.colorado.edu/html/fractions-equality/1.1.0-rc.2/phet/fractions-equality_all_phet.html
Version: 1.1.0-rc.2 2019-07-15 16:24:56 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362
Language: en-US
Window: 1536x751
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment] 2019-07-24 18:35
I don't notice it at all on chrome or firefox. I couldn't get your video to play but I will try again to hear what you hear. The only thing I hear is that click sound at the end of the ding, which I've brought up before, and can't un-hear for the life of me :)

**Comment by amanda-phet** [comment] 2019-07-24 18:37
Got your video to work, and I sort of hear it, but I don't think it's a major issue. (Also noticed you were on windows, so maybe that's why I didn't hear it on my mac). Did you check any other sims? I wonder if it's a fraction matcher issue or a vegas/tambo/vibe sort of issue. Either way, I don't see this as blocking for this sim.

**Comment by KatieWoe** [comment] 2019-07-24 18:38
>Didn't seem to happen when I tested published Build a Fraction, which uses similar sounds

**Comment by amanda-phet** [comment] 2019-07-24 18:40
@KatieWoe can you test in another sim in development? I think this new one uses vibe, right?

**Comment by KatieWoe** [comment] 2019-07-24 18:51
@amanda-phet I couldn't find a tambo (the new sound system as opposed to vibe) that used similar ding sounds.

**Comment by jonathanolson** [comment] 2019-07-25 07:57
I'm unaware of anything I could do that would affect/control this. @jbphet could we look into this together sometime?

**Comment by jbphet** [comment] 2019-07-31 22:51
@jonathanolson - sure, we can check it out.  I tried to take a quick look, but the sim isn't even loading on MS Edge for me at the moment.  I see the following in the console:

![image](https://user-images.githubusercontent.com/3082831/62253191-526df800-b3b2-11e9-95ec-b2e76b974d64.png)

Let me know if you understand why this is happening and how I might be able to test it.

**Comment by jonathanolson** [comment] 2019-08-15 08:15
@jbphet I'm honestly not sure what was happening. I was able to run require.js and built forms of fraction-matcher on both master and the 1.2 branch. All with Edge 44.17763.1.0 on Win10.

Can we collaborate to try to resolve the issue? And if the `super` keyword is an issue, we can try building the sim?

**Comment by jbphet** [comment] 2019-08-15 22:35
I'm still unable to run the RequireJS version on Edge 42.17134.1.0 on my Win 10 machine, but I can build and run, so I added some debug statements to see if there was anything odd going on.  I wasn't able to come up with any explanation.  When the sound starts playing, the audio context is enabled, the audio buffer has finished decoding, and the gain values of `SoundClip`'s gain node are reporting that they are at 1 - all of which would seem to indicate that the sound should play just fine.  Tracking down why it's NOT playing perfectly will probably take some time, since it doesn't seem like there is anything obvious going on.

I've run into several odd behaviors with sound-related functionality that is generally caused by the browsers not activating audio components until they are proven to be needed.  I'm betting that something like this is going on.  It would be interesting to try playing a nearly-silent sound on the first user interaction to see if that "clears the way" for subsequent sounds.

This issue doesn't really seem like a big priority to me, since it's subtle, doesn't have much of an impact on the user, and doesn't occur on all browsers, but I'm up for spending a little time collaborating on it.  @jonathanolson - how about Monday Aug 9 at 10 am (during core hours) to spend a little time working together on this?

**Comment by jonathanolson** [comment] 2019-08-19 16:30
@ariel-phet it seems that given the effort involved and the impact, I'd like to check whether additional time would be warranted for this issue? This seems like browsers may just improve their implementation and fix things in the future.

**Comment by ariel-phet** [comment] 2019-08-21 20:44
@KatieWoe great attention to detail, but I think probably for this "class" of sound issues they can just be ignored since the sound still plays but is just a bit "off" the first time.

@jonathanolson @jbphet thanks for the investigation, no need to spend more time.

Marking as 'wontfix' and closing

**Closed** 2019-08-21 20:45 UTC
Labels: type:bug, type:wontfix
